title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://www.nicolemaneth.com/VRUniverse
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: nicolem
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: nicole.maneth@gmail.com

google_analytics: ""
