title: VRUniverse
description: Put the Universe in your Pocket

url: http://www.nicolemaneth.com/
baseurl: "/VRUniverse"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: nicolem
   email: nicole.maneth@gmail.com

google_analytics: ""
